name: ðŸ§ª PyTest

on:
  # Run tests on all pushed branches
  push:
    branches: [main]
  # Run tests on PR, prior to merge to main & development
  pull_request:
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_pytest.yml@1.2.4
    with:
      image_name: ghcr.io/${{ github.repository }}
      tag_override: ${{ github.event_name == 'push' && 'ci' || '' }}
