name: pytest

on:
  # Run tests on all pushed branches
  push:
    branches:
      - "*"
  # Run tests on PR, prior to merge to main & development.
  pull_request:
    branches:
      - main
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Start CI Container
        run: >
          docker run -d --name fmtm_pytest
          -v "$GITHUB_WORKSPACE/osm_fieldwork:/home/appuser/.local/lib/python3.10/site-packages/osm_fieldwork"
          -v "$GITHUB_WORKSPACE/tests:/home/appuser/tests"
          -u root
          ghcr.io/hotosm/osm-fieldwork:ci
          sleep infinity

      - name: Run PyTest as appuser
        run: docker exec fmtm_pytest gosu appuser pytest
