name: pytest

on:
  # Run tests on all pushed branches
  push:
    branches:
      - "*"
  # Run tests on PR, prior to merge to main & development.
  pull_request:
    branches:
      - main
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    container:
      image: ghcr.io/hotosm/osm-fieldwork:ci
      volumes:
        # Mount / test files in commit
        - ./osm_fieldwork:/home/appuser/.local/lib/python3.10/site-packages/osm_fieldwork
        - ./tests:/home/appuser/tests
      options: --user root

    steps:
      - uses: actions/checkout@v3
      - name: Run pytest as appuser
        run: gosu appuser pytest
